### ISSUE TITLE
In horizontal bar mode, quick filters don't do anything

### ISSUE THREAD

**Issue by flenzen** [IagoSRL/TBX-Unified-Search#35]
If the quick filters (unread, starred, contact…) are displayed as a horizontal menu below the Unified Search bar (screenshot of what I mean attached), clicking them does not perform any action (button does not react, visually and no filtering occurs). If the filters are being displayed as a drop down menu, everything behaves normally.

Unified-Search version: 0.7.6
TB version: 52.6.0
![screenshot](https://user-images.githubusercontent.com/342447/37992994-864271e2-320d-11e8-8f85-6fce1b911dcb.png)

**Comment by oeekker** [comment]
This works for me on Windows 10, although it takes a couple of seconds to react if you have a lot of messages in the current folder. Can you check the contents of your error console to see if there's a message related to TBX-Unified Search after you've tried changing the search options in the horizontal view?

**Comment by flenzen** [comment]
After having restarted TB since yesterday, I cannot reproduce this error. I.e., also horizontal bar works as expected now. I shall reopen this issue if I manage to reproduce it.
